### ISSUE TITLE
👷 Add input version when workflow dispatch

### ISSUE THREAD

**Issue by anthonypillot** [size-up/freegamescatcher-core#159]
Add to this line an input to pick the version to deploy in the workflow dispatch:
https://github.com/size-up/freegamescatcher-core/blob/9b7a81d62f65f13d9afae627d15dcc0b375fbcc2/.github/workflows/ci-cd.yaml#L12

Something like:
```yaml
  workflow_dispatch: # allow manual trigger
    inputs:
      version:
        description: "Version to release (e.g. 1.2.3)"
        required: true
```

So think to develop a mechanism to switch between `${{ steps.version.outputs.nextVersion }}` and the input version.

Cf. this schema:

[workflow-dispatch-version.pdf](https://github.com/size-up/freegamescatcher-core/files/11373178/workflow-dispatch-version.pdf)
